In [7]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn

from pandas import Series, DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import classification_report

## 1) Cargamos el dataset
cachipun = pd.read_csv("dataset-prueba2.csv")
cachipun.head()

Muestra 1  Muestra 2  Muestra 3  Muestra 4  Muestra 5  Muestra 6  \
0       26.0        4.0        5.0        8.0       -1.0      -13.0   
1      -47.0       -6.0       -5.0       -7.0       13.0       -1.0   
2      -19.0       -8.0       -8.0       -8.0      -21.0       -6.0   
3        2.0        3.0        0.0        2.0        0.0       22.0   
4        6.0        0.0        0.0       -2.0      -14.0       10.0   

   Muestra 7  Muestra 8  Muestra 9  Muestra 10  ...  Muestra 56  Muestra 57  \
0     -109.0      -66.0       -9.0         2.0  ...       -28.0        61.0   
1       35.0      -10.0       10.0        -4.0  ...       -25.0        47.0   
2      -79.0       12.0        0.0         5.0  ...       -83.0         7.0   
3      106.0      -14.0      -16.0        -2.0  ...       -38.0       -11.0   
4      -51.0        5.0        7.0         0.0  ...        38.0       -35.0   

   Muestra 58  Muestra 59  Muestra 60  Muestra 61  Muestra 62  Muestra 63  \
0         4.0         8.0         5.0         4.0        -7.0       -59.0   
1         6.0         6.0         5.0        13.0        21.0       111.0   
2         7.0         1.0        -8.0         7.0        21.0       114.0   
3         4.0         7.0        11.0        33.0        39.0       119.0   
4        -8.0         2.0         6.0       -13.0       -24.0      -112.0   

   Muestra 64  resultado  
0        16.0          0  
1        15.0          0  
2        48.0          0  
3        43.0          0  
4       -69.0          0  

[5 rows x 65 columns]

In [8]:
cachipun.isnull().sum()


Muestra 1     0
Muestra 2     0
Muestra 3     0
Muestra 4     0
Muestra 5     0
             ..
Muestra 61    0
Muestra 62    0
Muestra 63    0
Muestra 64    0
resultado     0
Length: 65, dtype: int64

In [14]:
yy=cachipun['resultado']
cachipun=cachipun.drop(['resultado'],1)

In [19]:
cachipun.head()

Muestra 1  Muestra 2  Muestra 3  Muestra 4  Muestra 5  Muestra 6  \
0       26.0        4.0        5.0        8.0       -1.0      -13.0   
1      -47.0       -6.0       -5.0       -7.0       13.0       -1.0   
2      -19.0       -8.0       -8.0       -8.0      -21.0       -6.0   
3        2.0        3.0        0.0        2.0        0.0       22.0   
4        6.0        0.0        0.0       -2.0      -14.0       10.0   

   Muestra 7  Muestra 8  Muestra 9  Muestra 10  ...  Muestra 55  Muestra 56  \
0     -109.0      -66.0       -9.0         2.0  ...        21.0       -28.0   
1       35.0      -10.0       10.0        -4.0  ...      -105.0       -25.0   
2      -79.0       12.0        0.0         5.0  ...      -128.0       -83.0   
3      106.0      -14.0      -16.0        -2.0  ...       -54.0       -38.0   
4      -51.0        5.0        7.0         0.0  ...        60.0        38.0   

   Muestra 57  Muestra 58  Muestra 59  Muestra 60  Muestra 61  Muestra 62  \
0        61.0         4.0         8.0         5.0         4.0        -7.0   
1        47.0         6.0         6.0         5.0        13.0        21.0   
2         7.0         7.0         1.0        -8.0         7.0        21.0   
3       -11.0         4.0         7.0        11.0        33.0        39.0   
4       -35.0        -8.0         2.0         6.0       -13.0       -24.0   

   Muestra 63  Muestra 64  
0       -59.0        16.0  
1       111.0        15.0  
2       114.0        48.0  
3       119.0        43.0  
4      -112.0       -69.0  

[5 rows x 64 columns]

In [38]:
X = cachipun.iloc[0:len(cachipun),0:64]

In [39]:
y = yy
y.head(6600)

0       0
1       0
2       0
3       0
4       0
       ..
6595    2
6596    2
6597    2
6598    2
6599    2
Name: resultado, Length: 6600, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

from sklearn import tree
#Entrenamiento
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [41]:
#Predicciones
y_pred = clf.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[785  17  88]
 [  6 750  92]
 [ 69  99 721]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       890
           1       0.87      0.88      0.88       848
           2       0.80      0.81      0.81       889

    accuracy                           0.86      2627
   macro avg       0.86      0.86      0.86      2627
weighted avg       0.86      0.86      0.86      2627



In [42]:
##Regresion logistica

from sklearn.linear_model import LogisticRegression

#Aprendizaje
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
#Predicciones
y_pred = LogReg.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[401 240 249]
 [112 372 364]
 [175 340 374]]
              precision    recall  f1-score   support

           0       0.58      0.45      0.51       890
           1       0.39      0.44      0.41       848
           2       0.38      0.42      0.40       889

    accuracy                           0.44      2627
   macro avg       0.45      0.44      0.44      2627
weighted avg       0.45      0.44      0.44      2627



In [44]:
##random forest
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=15)
clf = clf.fit(X_train, y_train)

#Predicciones
y_pred = clf.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[870   1  19]
 [  3 798  47]
 [ 32  18 839]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       890
           1       0.98      0.94      0.96       848
           2       0.93      0.94      0.94       889

    accuracy                           0.95      2627
   macro avg       0.96      0.95      0.95      2627
weighted avg       0.95      0.95      0.95      2627

